### ISSUE TITLE
Turn into an add-on?

### ISSUE THREAD

**Issue by flatsiedatsie** [mrstegeman/photo-cycler-webthing#2]
Just out of curiosity, would it theoretically be possible to turn this into an add-on for the Gateway?

**Comment by mrstegeman** [comment]
The problem with doing that is locating files on the gateway, or even forcing the user to somehow upload their files.

**Comment by flatsiedatsie** [comment]
I was thinking/exploring (for another idea) that perhaps this could be done?:

- An add-on creates a thing, and this thing has a HTTP-link property (I believe I've seen this somewhere) which creates a little chain-icon. It links to `localhost:1234`.
- At the same time, the add-on starts a basic Python webserver at port 1234. There, the user can find a more complicated UX than the gateway currently [allows add-ons to have](https://github.com/mozilla-iot/gateway/issues/1505).

For example, a screensaver add-on could create a single screensaver thing. This thing has the link to the actual screensaver, which opens in a new window. In that new window the user can see pictures or upload new ones.

Could this work?

**Comment by mrstegeman** [comment]
Yes, I think that would work fine.
